[package]
name = "vision"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }

ort = { version = "2.0.0-rc.12", features = ["ndarray"] }
ndarray = "0.15"
image = "0.25"

anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }

nokhwa = { version = "0.10", features = ["input-native"] }