[package]
name = "safety-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
vision = { path = "../vision" }
ai-brain = { path = "../ai-brain" }
safety-engine = { path = "../safety-engine" }

slint = "1.16.1"
rfd = "0.17.2"

[build-dependencies]
slint-build = "1.16.1"